micronaut:
  application:
    name: pixRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyPixGrpc:
      address: 'localhost:50052'
      plaintext: true
      max-retry--attempts: 10
